use_frameworks!

platform :ios, '9.0'

target 'ZTTwoAttritedString_Example' do
  pod 'ZTTwoAttritedString', :path => '../'

  target 'ZTTwoAttritedString_Tests' do
    inherit! :search_paths

    
  end
end
